### ISSUE TITLE
S3 connection never re-used?

### ISSUE THREAD

**Issue by aectann** [thumbor-community/aws#10]
I've just noticed that ```get_connection``` method from ```connection.py``` never reuses an S3 connection, since module level ```connection``` variable is never assigned to anything but None. I wonder if that's by design, and what are possible drawbacks of keeping a reference to an S3 connection once it was initialized?

**Comment by dhardy92** [comment]
this would be a good way to handle it ? https://boto.readthedocs.org/en/latest/ref/boto.html#boto.connection.ConnectionPool

**Comment by Bladrak** [comment]
It actually should be a singleton, since the module is never re-instantiated, shouldn't it?
If it isn't, the fast way would be to store it within the thumbor's context (but this being related to the request, not sure about the gain). The best way would be to use the connection pool as @dhardy92 suggested.

**Comment by aectann** [comment]
@dhardy92 I believe S3Connection uses the connection pool under the hood. So if reference to the connection is retained, connections should be pooled already.

**Comment by Bladrak** [comment]
@aectann I just re-read the code and noticed what you said. I fixed that in commit https://github.com/thumbor-community/aws/commit/12b961530ed297b92533978883d143996876b920 ; is that ok with you?

**Comment by aectann** [comment]
@Bladrak I think you're missing a ```global connection``` declaration in the function, without it the module level ```connection``` variable won't be modified. Here is more context http://stackoverflow.com/questions/7060711/accessing-module-level-variables-from-within-a-function-in-the-module

**Comment by Bladrak** [comment]
Yeah just noticed I broke the tests :/ Let me fix that ;)

**Comment by Bladrak** [comment]
Should be ok now :)

**Comment by aectann** [comment]
@Bladrak Awesome! I think we could close this issue now.
