### ISSUE TITLE
RESULT_STORAGE_AWS_STORAGE_ROOT_PATH have impact on tc_aws.storages.s3_storage

### ISSUE THREAD

**Issue by dhardy92** [thumbor-community/aws#11]
following #4 setting RESULT_STORAGE_AWS_STORAGE_ROOT_PATH other than '/' make ```tc_aws.storages.s3_storage``` fail at getting original keys

This should only impact on ```tc_aws.result_storages.s3_storage```

We should fine a way to merge those code base and avoid duplication.

**Comment by masom** [comment]
Moving the file handling logic to a different module that is shared for both classes would be great.

**Comment by Bladrak** [comment]
@masom @dhardy92 PR #16 should fix the module part, what do you think of this solution?

**Comment by masom** [comment]
Looks ok to me.

**Comment by Bladrak** [comment]
#17 should fix this issue (without the refactoring part). Does it seem ok to you @dhardy92 ?

**Comment by Bladrak** [comment]
Whenever you get the chance to close this issue @dhardy92 :)
