### ISSUE TITLE
Trouble in DELETE Request

### ISSUE THREAD

**Issue by Moginu** [thumbor-community/aws#123]
Hi team,
I'm using tc_aws.storages.s3_storage as my Storage in thumbor. And When I'm using the REST API's DELETE, it cannot truly delete the file.

There is no error when it's running. 
Actually, in the class AwsStorage, if I remove the yield in the function remove(), the file can be deleted.

Do you have any idea about it?

Thank you.

**Comment by Bladrak** [comment]
Related to https://github.com/thumbor-community/aws/issues/39

**Comment by Bladrak** [comment]
Closing as this should be fixed by the merged MR. Feel free to re-open if that wasn't the case.
