### ISSUE TITLE
Support thumbor v7.x.

### ISSUE THREAD

**Issue by b3g00d** [thumbor-community/aws#144]
as title

**Comment by Bladrak** [comment]
see #142

**Comment by michaelurban** [comment]
Is there an ETA for the 7.x update?

**Comment by bagipriyank** [comment]
this is blocking us from testing thumbor 7.x as well.

**Comment by heynemann** [comment]
There's a PR on thumbor (https://github.com/thumbor/thumbor/pull/1342) that will allow legacy extensions to be used. Can someone help test thumbor with S3 using the new compatibility layer?

**Comment by dominik-bln** [comment]
I just tried testing the compatibility layer, but running into the following problem:

<img width="1071" alt="Screenshot 2021-12-01 at 16 31 39" src="https://user-images.githubusercontent.com/855119/144263688-1c52c1e7-d35b-483a-b95d-eadb3d237cea.png">

Would it be possible to publish a prerelease version that allows thumbor 7?

**Comment by dominik-bln** [comment]
I got thumbor 7 and tc_aws installed at the same time via `pip install --no-deps tc_aws==6.2.15` and specifying the `tc_aws` deps manually. Now I am running into compatibility issues with Python 3:

```bash
thumbor_1  |   File "/usr/local/lib/python3.10/site-packages/tc_aws/loaders/__init__.py", line 9, in <module>
thumbor_1  |     import urllib2
thumbor_1  | ModuleNotFoundError: No module named 'urllib2'
```

So there is at least work to do in first porting the package to Python 3, before the compatibility layer can be tested.

**Comment by dominik-bln** [comment]
Nevermind, looks like compat layer is not even needed with this PR https://github.com/thumbor-community/aws/pull/147

**Comment by peterrus** [comment]
And don't forget @jimas14! (:

**Comment by Bladrak** [comment]
Thanks @jimas14 as well! Sorry I missed you :)

@peterrus I'd wait a few weeks to see if there are feedbacks from users before merging this to master and releasing a stable version. Ideally we should fix the warnings indeed.

**Comment by Tenzer** [comment]
What's needed before a release can be made with the Thumbor 7 related changes?

**Comment by Bladrak** [comment]
@Tenzer there's an alpha release available. We'll probably release a stable version in the coming weeks if no issues arise.

**Comment by Tenzer** [comment]
Ah, I had missed that. Thanks, I'll try it out soon.

**Comment by charcoal3r** [comment]
Hi, have been running this in production for a few weeks now without any issues. Processing hundredths of requests per week on about 5 instances combined. Just created this account to provide some feedback (:

**Comment by heynemann** [comment]
Awesome fedback @charcoal3r!!! Thank you for that!

**Comment by heynemann** [comment]
We have many companies already running Thumbor 7 for real for a while now :) Go for it! Let us know how it goes.

**Comment by heynemann** [comment]
Regarding thumbor-community/aws I'll let the committers talk about it.

**Comment by aaugustin** [comment]
After posting, I discovered https://github.com/thumbor/thumbor-aws, which is probably the correct answer here.

**Comment by Bladrak** [comment]
Forgot about that, I'll release a stable release this week.
Nice seeing you here @aaugustin by the way ;-)

**Comment by peterrus** [comment]
@Bladrak That'd be nice!

By the way, do we now have two thumbor plugins that provide AWS functionality? Do we want that?

**Comment by Bladrak** [comment]
@peterrus I wasn't aware that https://github.com/thumbor/thumbor-aws existed (I'm mostly maintaining this repo when I have some time), maybe this one is no longer needed. @heynemann maybe you can give a bit more insight? What are the main differences? Should we deprecate this repo in favor of the one on Thumbor org?

**Comment by heynemann** [comment]
TBH @Bladrak I created the other one just as a means to move adoption of 7.0.0 forward. There's not much different between them. Probably mine has bugs that this one doesn't :)

**Comment by Bladrak** [comment]
Version 7.0.2 has been released, and is stable. I'm closing this with this release, thanks to everyone who contributed on this!
@heynemann let me know if you want to rationalise this, I'm not sure 2 repos make sense. I'm happy to help, whether in deprecating this repo, or moving it to the Thumbor org.
