### ISSUE TITLE
Handle multiprocessing

### ISSUE THREAD

**Issue by Bladrak** [thumbor-community/aws#21]
As seen in #14 

> There is a high chance the aws loader is blocking the i/o loop. Anything that isn't made for Tornado tends to block the loop ( like the redis loader, but it's so fast we don't see the blocking ).
> One way to go around this would be to use the multiprocessing module and queue requests to a separate process pool that will fetch the images from AWS and pass them back to the main process using queues.
> Might require a little bit of refactoring but it would probably help with concurrency.
> http://tornado.readthedocs.org/en/latest/process.html might help with that.
> https://gist.github.com/FZambia/5756470
> - @masom

**Comment by masom** [comment]
https://github.com/nanvel/tornado-botocore might be an alternative.

**Comment by heynemann** [comment]
I like @masom option better! :)

**Comment by aichholzer** [comment]
There is always the option to use this one: https://github.com/99designs/thumbor_botornado

**Comment by Bladrak** [comment]
Given thumbor_botornado doesn't seem highly maintained, and uses botornado which hasn't been update in years, I'll try with tornado-botocore first. I may give the others a try if botocore doesn't work out.

**Comment by masom** [comment]
Awesome to see this being closed.

**Comment by heynemann** [comment]
Congrats!!!

**Comment by Bladrak** [comment]
Thanks! :speedboat:

**Comment by aichholzer** [comment]
`Awesome!`
