### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by Bladrak** [thumbor-community/aws#23]
Technical doc is mis-formatted, we should have a generation script & pass on the code to fix it.

**Comment by aoqfonseca** [comment]
Can you explain better what need to do here?  Can we use something link sphinx to generate our docs?

**Comment by Bladrak** [comment]
Basically what's needed is to use the same system as https://github.com/thumbor-community/core to generate the doc ; so sphinx and RST indeed :)

**Comment by aoqfonseca** [comment]
Ok. I got it!!!

**Comment by aoqfonseca** [comment]
I put Sphinx in the project and create skeleton for docs
Now it's possible to start write docs.  Can i make a pull request with this?

**Comment by Bladrak** [comment]
Yep sure, feel free :) (FYI, it seems the skeleton hasn't been committed, you may want to add a .gitkeep file in the folders created).

**Comment by aoqfonseca** [comment]
I forgot add folder and files. I fix that now. Tks.
