### ISSUE TITLE
S3_ALLOWED_BUCKETS not working properly in conjunction with watermark

### ISSUE THREAD

**Issue by isurugiu** [thumbor-community/aws#30]
As discussed with Bladrak I am opening this issue in respects of the S3 loader not working properly.

Please see the below config and logs.

S3_LOADER_BUCKET = 'my-bucket-xxx'
S3_ALLOWED_BUCKETS = ['my-bucket-xxx']
AWS_ENABLE_HTTP_LOADER=True
 
2015-09-28 13:51:13 thumbor:DEBUG STATSD: storage.miss:1|c
2015-09-28 13:51:13 tornado.access:WARNING 404 GET /unsafe/fit-in/525x650/filters:watermark(/my-bucket-xxx/watermark.png,0,0,0)/my-bucket-xxx/APAP131C78CE.jpg (127.0.0.1) 5.05ms

**Comment by Bladrak** [comment]
Oddly enough, I found a temporary fix for this issue: if you have storage/result_storage enabled, once you load the watermark image directly (GET /unsafe/my-bucket-xxx/watermark.png), you can use it as a watermark.
We need to check which loader/storage is used to load watermark images.

**Comment by Bladrak** [comment]
Fixed in dca3401289e5b85256d02ee144133fa87742cceb & published on pypi version 2.1.2 https://pypi.python.org/pypi/tc_aws/2.1.2

@isurugiu feel free to test this version and reopen this issue if this isn't fixed :)

**Comment by isurugiu** [comment]
Will do. Thank you.
