### ISSUE TITLE
Are result storage uploads async?

### ISSUE THREAD

**Issue by nykolaslima** [thumbor-community/aws#34]
I'm wondering if I configure result storage to use S3 implementation, these uploads are going to be async or they will block the thread?

**Comment by Bladrak** [comment]
They are blocking at the moment, as thumbor's doesn't currently handle async writing.

**Comment by Bladrak** [comment]
@nykolaslima is this answer satisfying for you? If so, could you close this issue?

**Comment by aoqfonseca** [comment]
I believe that new version of thumbor this operations are async.

**Comment by Bladrak** [comment]
If you look at the current result file_storage class, put operations aren't asynchronous: https://github.com/thumbor/thumbor/blob/master/thumbor/result_storages/file_storage.py#L32

**Comment by nykolaslima** [comment]
Dammit, we already suspect that it's a sync operation :cry: 

We are migrating from result storage with `file_storage` to `s3_storage`. But our previous machine was processing more photos per machine, using less CPU. We believe that the sync upload operation is causing this.

@robertomarin

**Comment by aoqfonseca** [comment]
@Bladrak 

You're right.... Just get operation was async. Sorry about that.

**Comment by Bladrak** [comment]
@aoqfonseca no worries :)

**Comment by nykolaslima** [comment]
@Bladrak there is some reason to do not support it as a async operation?

**Comment by Bladrak** [comment]
If you have to handle concurrent requests of the same image, you may want to avoid allowing async yes. Beside that, I'm not sure, maybe to check with @masom ?

**Comment by masom** [comment]
@nykolaslima They now are as of Thumbor 5.2.0+

**Comment by masom** [comment]
https://github.com/thumbor/thumbor/pull/573

**Comment by Bladrak** [comment]
@masom given the existing storage only handle get as an async op, I didn't notice you edited the writing op as well :) Shouldn't be a lot of work to implement it on tc_aws side, however I won't get the time in the immediate future.
@nykolaslima if you get the time to implement it, shouldn't be too complicated :)

**Comment by nykolaslima** [comment]
I'll take a look at it @Bladrak

**Comment by Bladrak** [comment]
Thanks a lot :)

**Comment by masom** [comment]
@Bladrak The operation now happens in the tornado IO loop. The result storage can now operate fully async and is already not blocking the current response.

**Comment by Bladrak** [comment]
Done within https://github.com/thumbor-community/aws/tree/thumbor_6 branch
