### ISSUE TITLE
AWS credentials not cached - rising number of network connections

### ISSUE THREAD

**Issue by bob3000** [thumbor-community/aws#37]
Hi,
it seems that the AWS credentials which are fetched with boto through the instance meta are not cached inside the plugin at the moment. Since boto itself will not cache the credentials they will be fetched on every call to S3.
The latter will cause a constantly rising number of network connections waiting for credentials (probably due to API rate limiting) which causes thumbor to use 100% CPU. The whole thing goes on until the OS finally runs out of file descriptors and goes down.
A workaround is to use a .boto file instead of the credentials from the instance's role.

**Comment by Bladrak** [comment]
Hello @bob3000 and thanks for reporting this issue. How would you handle caching the credentials within the plugin? We need to be compatible with a role based authentication as well, which is why we let boto handle the authentication.

**Comment by bob3000** [comment]
Hi Bladrak,
thanks for the quick reply. I'm not sure if it will work this way but wouldn't it be possible to fetch the credentials only every 15 min and save them in between into a variable which can be handed over to the S3Connection constructor when ever a connection is instantiated?

Unfortunately I'm not entirely sure anymore if the issue I described here is really the cause of the problems I experience. Though it got a little better since I put the AWS credentials into a file.

But still I have the problem that Thumbor begins to use 100% CPU after receiving traffic for a like 2 minutes which is accompanied by a rising number of network connections and a rising memory consumption until the machine is completely exhausted and Thumbor gets OOM killed.
At first I thought that the boto calls to the instance meta url would be to blame for that but does not seem to the solution to this problem. Any ideas what could block?

Though Thumbor receives a lot of traffic I'm quite sure that the hardware is not the problem. I'm running 2 C3.large machines each running 4 Thumbor processes behind an Nginx. I see almost no ease even if I run 6 machines.

I'd be very thankful for any suggestions how to further debug this.

Here is my thumbor config
```
MAX_WIDTH = 1000
MAX_HEIGHT = 1000
QUALITY = 60
WEBP_QUALITY = 60
AUTO_WEBP = True
MAX_AGE = 365 * 24 * 60 * 60
MAX_AGE_TEMP_IMAGE = 60
LOADER = 'tc_aws.loaders.s3_loader'
STORAGE = 'thumbor.storages.no_storage'
SECURITY_KEY = 'MY_SECURE_KEY'
ALLOW_UNSAFE_URL = True
ALLOW_OLD_URLS = False
FILTERS = [
        'thumbor.filters.quality',
        'thumbor.filters.frame',
        'thumbor.filters.rotate',
        'thumbor.filters.format',
        'thumbor.filters.max_bytes',
        'thumbor.filters.no_upscale',
    ]
RESULT_STORAGE = 'tc_aws.result_storages.s3_storage'
RESULT_STORAGE_STORES_UNSAFE = True
USE_CUSTOM_ERROR_HANDLING = True
ERROR_HANDLER_MODULE = 'thumbor.error_handlers.sentry'
SENTRY_DSN_URL = 'XXX'
AWS_ACCESS_KEY = None
AWS_SECRET_KEY = None
TC_AWS_REGION = 'us-east-1'
TC_AWS_ALLOWED_BUCKETS = ['XXX', 'XXX']
TC_AWS_LOADER_BUCKET = 'XXX'
TC_AWS_RESULT_STORAGE_BUCKET = 'XXX'
TC_AWS_STORAGE_SSE = False
TC_AWS_STORAGE_RRS = False
METRICS = 'thumbor.metrics.statsd_metrics'
STATSD_HOST = 'XXX'
STATSD_PREFIX = 'thumbor.thumbor'
ENABLE_ETAGS = False
```

**Comment by Bladrak** [comment]
Could you specify which version of tc_aws you're using?
Did you try the same requests with another storage than tc_aws? Did you get different results?

**Comment by bob3000** [comment]
I'm using the the latest version from pypi. Unfortunately I cannot try another storage than tc_aws to load the images since all our images are on S3. However I tried to write the results to disk without experiencing a mentionable improvement.
We have been using Thumbor before with the older version of the plugin before it was forked and did not have any problems as all.

I did a bit of profiling today using [plop](https://github.com/bdarnell/plop) and found that a lot of time seems to be spend on SSL hand shakes and also in the json library which makes me think if the S3 connections are maybe not properly reused which might create a lot of overhead. I'll attach you some screen shots.

<img width="604" alt="capture d ecran 2015-12-16 a 17 18 57" src="https://cloud.githubusercontent.com/assets/1550574/11848524/d23432da-a41a-11e5-9412-1bf65fb0dfea.png">
<img width="863" alt="capture d ecran 2015-12-16 a 17 19 27" src="https://cloud.githubusercontent.com/assets/1550574/11848526/d238383a-a41a-11e5-9339-9e23b667bcd2.png">

**Comment by Bladrak** [comment]
Thanks for this analysis. I'll try to take a look whenever I get the chance :)

**Comment by bob3000** [comment]
No worries. I'll open a pull request later today. With the fix I implemented yesterday the servers run much smoother now. I just want to let them run for a couple of hours to make sure I didn't miss anything.

**Comment by Bladrak** [comment]
Great, thanks a lot! :)

**Comment by Bladrak** [comment]
@bob3000 I'm guessing PR #38 fixes this?

**Comment by bob3000** [comment]
Yes, that should fix it. Thank you very much on doing a great job on maintaining this important Thumbor plugin :+1:

**Comment by Bladrak** [comment]
It's a pleasure :) I'm closing this.
