### ISSUE TITLE
thumbor_aws does not return a 404 when it fails to find an image in the s3 bucket.

### ISSUE THREAD

**Issue by etcsayeghr** [thumbor-community/aws#41]
Hi there,

I notice in the logs that when tc_aws fails to find an image in the bucket it gets a 404 from the S3 bucket, but it does not propagate that 404 out to the http request to thumbor.

Am I doing something wrong?

**Comment by dhardy92** [comment]
Hello,
May you post your config (loader or storage) without key and test case ( imaging or image_resource handlers )  ?

**Comment by etcsayeghr** [comment]
CONFIG:
----
LOADER = 'tc_aws.loaders.s3_loader'

TC_AWS_REGION = 'REDACTED'
TC_AWS_LOADER_BUCKET = 'REDACTED'
TC_AWS_LOADER_ROOT_PATH = ''
----

test case would be http://thumbor/unsafe/300x300/imagethatdoenstexist.png

**Comment by Bladrak** [comment]
I'll take a look at this when I'll be able to test #36

**Comment by etcsayeghr** [comment]
Please let me know. That config is literally the entirety of my config. Perhaps I am missing something in the config to make it give me a 404 when it gets a 404 from S3?

**Comment by etcsayeghr** [comment]
This is what I get in the console when running thumbor manually, if this helps:

2016-01-12 19:41:00 thumbor:WARNING ERROR retrieving image from S3 atest.png: {'ResponseMetadata': {'HTTPStatusCode': 404, 'HostId': 'REDACTED', 'RequestId': 'REDACTED'}, 'Error': {'Message': 'The specified key does not exist.', 'Code': 'NoSuchKey', 'Key': 'atest.png'}}

but the thumbor server then does not return an http response / error, and just lets it time out.

**Comment by etcsayeghr** [comment]
I can see the problem, its in line: 34 of S3_loader.py
https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/s3_loader.py

You log that you got an error but you dont ever send a callback, so your loader just hangs.

**Comment by Bladrak** [comment]
I don't have my credentials to publish a new release right now, I'll try to do this this week-end if that's alright :)

**Comment by etcsayeghr** [comment]
Yes thank you very much!

**Comment by Bladrak** [comment]
@etcsayeghr the version 2.0.12 has been published on pypi, thanks for your contribution, I'm closing this now :)
