### ISSUE TITLE
Is it possible to configure a custom host in version 2.0.0?

### ISSUE THREAD

**Issue by pietervogelaar** [thumbor-community/aws#42]
In version 1.3.2 the following can be configured:

```
# Optional additional configuration for the Boto-Client used to access S3.
# see http://boto.readthedocs.org/en/latest/ref/s3.html?highlight=boto.s3.connection.s3connection#boto.s3.connection.S3Connection
# for all available config options
BOTO_CONFIG = {
    'host': 'fakes3.local.dev',
    'is_secure': False
}
```

What would be the way to configure this in version 2.0.0?

**Comment by Bladrak** [comment]
tc_aws doesn't handle config at all. Everything is done through botocore configuration, which means that you can do this, but by using the configuration file for instance, as specified in: http://boto.readthedocs.org/en/latest/boto_config_tut.html

Feel free to close this issue if that answered your question.

**Comment by pietervogelaar** [comment]
Yeah, I can for example configure the following fine with boto3:

```
[Credentials]
aws_access_key_id = <your_access_key_here>
aws_secret_access_key = <your_secret_key_here>
```

But changing the host seems impossible.

**Comment by Bladrak** [comment]
It seems the ``host`` option doesn't exist in boto. What do you want to use it for?

**Comment by pietervogelaar** [comment]
Our company uses a private S3 object store. So it works just the same like Amazon, but it's another host.

**Comment by Bladrak** [comment]
You might be looking at the proxy configuration then: http://boto.readthedocs.org/en/latest/boto_config_tut.html#boto

**Comment by Bladrak** [comment]
I'm closing this issue. Feel free to re-open it if your question hasn't been answered.
