### ISSUE TITLE
latest botocore does not allow private s3 urls

### ISSUE THREAD

**Issue by phoet** [thumbor-community/aws#47]
using the pre-signed-loader is currently broken for private S3-urls because of an [issue in botocore](https://github.com/boto/botocore/issues/601).

/cc @Bladrak

**Comment by Bladrak** [comment]
Thanks @phoet we'll see how the issue https://github.com/boto/botocore/issues/601 goes :)

**Comment by Bladrak** [comment]
@phoet can we close this?

**Comment by phoet** [comment]
unfortunately, there is still an issue open https://github.com/boto/botocore/issues/846

**Comment by Bladrak** [comment]
Ok, we'll keep tracking this then, thanks :)

**Comment by phoet** [comment]
closed with https://github.com/boto/botocore/issues/846
