### ISSUE TITLE
Implement Expiration parameter

### ISSUE THREAD

**Issue by gmarchand** [thumbor-community/aws#51]
Hello, 

In default configuration of Storage in thumbor project. I can configure `EXPIRATION`. It doesn't seem to be implemented in AWS Storage.

```
################################# File Storage #################################
## Expiration in seconds for the images in the File Storage. Defaults to one
## month
## Defaults to: 2592000
#STORAGE_EXPIRATION_SECONDS = 2592000

```
 
```
################################ Result Storage ################################
## Expiration in seconds of generated images in the result storage
## Defaults to: 0
#RESULT_STORAGE_EXPIRATION_SECONDS = 0
```

**Comment by dhardy92** [comment]
I suggest you to implement a bucket policy on aws S3 for this. 
It avoid unnecessary round-trip for Thumbor and ensure every objects are treat (not only those requested via Thumbor)

**Comment by Bladrak** [comment]
Closing this issue as AWS recommended way is the one suggested by @dhardy92. Feel free to reopen if needed.
