### ISSUE TITLE
Remotecv fails using tc_aws.s3_loader

### ISSUE THREAD

**Issue by eduherraiz** [thumbor-community/aws#54]
I'm trying to configure remotecv in order to use the tc_aws.loaders.s3_loader

I can see this error logged:
```
ERROR:pyres.worker:(Job{Detect} | remotecv.pyres_tasks.DetectTask | [u'all', u'path/to/image/s3/image.jpg', u'path/to/image/s3/image.jpg']) failed: 'module' object has no attribute 'load_sync'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyres/worker.py", line 253, in process
    return job.perform()
  File "/usr/local/lib/python2.7/site-packages/pyres/job.py", line 55, in perform
    return payload_class.perform(*args)
  File "/usr/local/lib/python2.7/site-packages/remotecv/pyres_tasks.py", line 11, in perform
    image_data = config.loader.load_sync(image_path)
AttributeError: 'module' object has no attribute 'load_sync'
```

Versions:
```
argparse==1.2.1
envtpl==0.4.1
boto==2.38.0
dateutils==0.6.6
numpy==1.9.2
pyremotecv==0.5.0
remotecv==2.1.0
opencv-engine==1.0.1
redis==2.4.12
thumbor==5.2.1
tc-aws==2.1.1
tc-core==0.3.0
tc-shortener==0.2.2
raven==5.10.1
```

**Comment by eduherraiz** [comment]
The remotecv worker always use the load_sync function:
https://github.com/thumbor/remotecv/blob/cab924befc7b715de43e6de230452ac196a173d0/remotecv/pyres_tasks.py#L12

There is any way to use tc_aws to load s3 images the same way?

**Comment by eduherraiz** [comment]
I believed the format of loader was the same in remotecv and thumbor. 
I will prepare a new loader for remotecv.

**Comment by eduherraiz** [comment]
The loader is ready here: https://github.com/APSL/remotecv_aws

**Comment by Bladrak** [comment]
Great work! Feel free to submit a PR if you'd like to merge it within tc_aws :)

**Comment by eduherraiz** [comment]
Thank you!
I think it's quite different like to maintain a different package.
(We're not using thumbor configuration system or tornado to get the image)
For the moment we published to PyPI: https://pypi.python.org/pypi/remotecv_aws/0.1

Maybe, the good option is move the repository under thumbor-community organization...

**Comment by Bladrak** [comment]
Yes that's also an option :) @masom what do you think?
