### ISSUE TITLE
The result storage (S3) is not very helpfull for signed keys and safe urls

### ISSUE THREAD

**Issue by gabn88** [thumbor-community/aws#55]
Everytime a page loads, my backend creates the images with different signed keys. Thumbor analyses these images and creates thumbnails on-the-fly. The results of thumbor all get stored in the result storage (S3 storage) as different images, because of the changing safe url thumbor key and the different amazon s3 signing key. It would be nice if it could detect and omit those keys.

**Comment by Bladrak** [comment]
Which keys would you like to detect and omit precisely? Could you give concrete examples to help understanding your request?

**Comment by gabn88** [comment]
Sorry for my bad description of the problem.

# The scenario
- Use http loader with safe urls and private images that are stored on amazon (and unlocked by pre-signed keys)
- I make a thumb of this url:
https://mybucket.s3.amazonaws.com/SomeImage.png?Signature=SomeSignature&Expires=Sometime&AWSAccessKeyId=Somekey
- So I call thumbor using this url:
https://myprotectedthumborservice.com/`MYSAFEURLKEY`/fit-in/192x192/`https%3A//mybucket.s3.amazonaws.com/SomeImage.png?Signature=SomeSignature&Expires=Sometime&AWSAccessKeyId=Somekey`

# The problem
- Every image is stored as a different image. For example the image above:
https://mythumbsbucket.s3.amazonaws.com/MYSAFEURLKEY/fit-in/192x192/https%253A//mybucket.s3.amazonaws.com%253A443//SomeImage.png?Signature=SomeSignature&Expires=Sometime&AWSAccessKeyId=Somekey/webp

- Since on every request my client gets another Thumbor MYSAFEURLKEY and different SomeSignature, Sometime and Somekey, every image gets stored as a new image and the result storage is useless.

# The solution (in words, sadly I'm not capable enought to implement this):
1. Check if httploader and aws resultstorage is used, then
    1. Remove MYSAFEURLKEY
    2. remove everything after ? or %3F
    3. then store image as usual.

**Comment by Bladrak** [comment]
Thanks for your detailed report :)

I think this will be pretty hard to implement, given it will impact both thumbor and this repository (the same logic must be performed as well on thumbor). An easier solution for you might be to use the s3 loader instead of the http loader, hence having the security handled between thumbor & s3 directly, so you may avoid having to pass Signature, Expires & AWSAccessKeyId parameters within your URLs. Is this solution possible for your implementation?

**Comment by gabn88** [comment]
Sadly this is not possible, as the permissions on the objects might change and those permissions are stored in a seperate (locked) application. This is also why I needed to use pre-signed keys. Which work fine, except for the result storage.

Also I'm wondering if every thumbor backend includes the SAFEURLKEY in the result storage? Because this is bound to change a lot of times (a.k. every request), to make sure that the request is safe.. and thus it would generate everytime a different result image, making the result backend useless?

Wouldn't it be possible to make a custom http_loader that creates this behaviour (just thinking out loud)?

**Comment by Bladrak** [comment]
The SAFEURLKEY needs to change only when the requests URL changes (in your case, each request, given you need to sign the requested image url). As you said, the result storage is useless in this case, as is any caching mechanism (storage as well).

You'll need to implement this behavior in a custom http_loader, but also in the storage & result storage, which would require quite some work.

**Comment by gabn88** [comment]
I already was afraid this was going to be the case. :(

Thanks for your help though. I will disable the caching mechanism completely for now. Hopefully one day I will find a better solution.

**Comment by gabn88** [comment]
By the way, I just found out that the storages (thus not resultstorages) have already an option to omit the SAFEURLKEY! So there might be hope... ;)
