### ISSUE TITLE
Thumbor - tc_aws - result_storage error

### ISSUE THREAD

**Issue by fredjsf** [thumbor-community/aws#58]
I'm trying install Thumbor with tc_aws and I have a problem with result_storage.

The image can not be saved in result bucket and Thumbor return error that cannot be debugged.

Someone can help me?

Thanks,

Fred

[console.out.txt](https://github.com/thumbor-community/aws/files/278531/console.out.txt)
[thumbor.cfg.txt](https://github.com/thumbor-community/aws/files/278532/thumbor.cfg.txt)

**Comment by dhardy92** [comment]
"%3D" is strange to me at the end of HMAC signature. are you sure ?

**Comment by fredjsf** [comment]
Thaks for reply.

I think is that correct. I'm using libthumbor
The "%3D" is output for aws s3. The thumbor output is 

thumbor:DEBUG Cleaning key: UgCH96k1fNiFS-fR_Dgh2B-Hujs=/122x101/smart/Koala.jpg

**Comment by fredjsf** [comment]
root@ip-172-31-28-15:/environments/thumbor# pip list
apt-xapian-index (0.45)
argparse (1.2.1)
aws (0.2.5)
awscli (1.10.35)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
boto (2.40.0)
botocore (1.4.25)
certifi (2016.2.28)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.3.3)
configobj (4.7.2)
derpconf (0.7.3)
docutils (0.12)
Fabric (1.11.1)
futures (3.0.5)
html5lib (0.999)
jmespath (0.7.1)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
libthumbor (1.3.2)
oauth (1.0.1)
PAM (0.4.2)
paramiko (1.17.0)
pbr (1.10.0)
pexif (0.15)
pgmagick (0.5.7)
Pillow (3.2.0)
pip (1.5.4)
prettytable (0.7.2)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycurl (7.19.3)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-dateutil (2.5.3)
python-debian (0.1.21-nmu2ubuntu2)
python-magic (0.4.11)
pytz (2016.4)
PyYAML (3.10)
requests (2.10.0)
rsa (3.4.2)
s3transfer (0.0.1)
setuptools (3.3)
singledispatch (3.4.0.3)
six (1.10.0)
ssh-import-id (3.21)
statsd (3.2.1)
stevedore (1.14.0)
tc-aws (6.0.1)
thumbor (6.0.1)
tornado (4.3)
tornado-botocore (1.0.2)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.15.1)
virtualenv (15.0.2)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)

**Comment by fredjsf** [comment]
The problem is body  : <StringIO.StringIO instance at 0x7fe33f6f9a28> and cannot be converted to utf8

2016-06-05 19:08:22 tornado_botocore.base:DEBUG Making request for OperationModel(name=PutObject) (verify_ssl=True) with params: {**'body': <StringIO.StringIO instance at 0x7fe33f6f9a28>**, 'url': u'https://s3-us-west-2.amazonaws.com/thumbor-centraldoevento/result/evCgqEl1KGAAxWRLVFfNat7ySwc%3D/100x100/smart/Koala.jpg', 'headers': {'User-Agent': 'Botocore/1.4.25 Python/2.7.6 Linux/3.13.0-74-generic', u'x-amz-storage-class': 'STANDARD'}, 'query_string': {}, 'url_path': u'/thumbor-centraldoevento/result/evCgqEl1KGAAxWRLVFfNat7ySwc%3D/100x100/smart/Koala.jpg', 'method': u'PUT'}

**Comment by dhardy92** [comment]
I suspect you are trying to upload (PUT) image on thumbor API endpoint (`/unsafe` or `/<hmac sign>`) instead of REST enpoint ( `/image` )

But `PUT` on API endpoint would result with "405 Method not allowed" (read only)

What is the command line you run ?

**Comment by fredjsf** [comment]
I'm using hmac url signed using libthumbor (python lib). I reinstalled server yesterday and the problem persist.

http://127.0.0.1:9000/evCgqEl1KGAAxWRLVFfNat7ySwc=/100x100/smart/Koala.jpg

Thumbor get image from aws, run commands, but result does not save in aws.

**Comment by ddrager** [comment]
Also seeing this same error message when using S3 storage or result_storage engine:

```"Expected bytes, unicode, or None; got %r" % type(value)```

Thumbor spits out this error on storage:

```2016-06-10 16:55:47 thumbor:ERROR [BaseHandler] get_image failed for url `http%3A//i47.tinypic.com/n2mhqs.jpg`. error: `Expected bytes, unicode, or None; got <type 'instance'>`
2016-06-10 16:55:47 tornado.access:ERROR 500 GET /yLOrlrD5fbVYOu_2QsLoztH_5pU=/http%3A%2F%2Fi47.tinypic.com%2Fn2mhqs.jpg (127.0.0.1) 537.69ms```

If I enable the default file storage I can at least get Thumbor to output the file, but I still get that same error message when trying to store the result in S3.

Looks like this plugin is mangling the = and : characters. Is this actually a problem in tornado/escape.py?

**Comment by fredjsf** [comment]
I upgrade thumbor, libthumbor and tc_aws and the error stoped.

This issue could be closed for current version.

**Comment by Bladrak** [comment]
Ok then, thanks for the feedback @fredjsf ; @ddrager do you have the issue after upgrading?

**Comment by Bladrak** [comment]
Closing this issue as there hasn't been much activity on it. Feel free to re-open if it happens again.
