### ISSUE TITLE
S3 path using "?" not functionnal since thumbor 6

### ISSUE THREAD

**Issue by dhardy92** [thumbor-community/aws#59]
For legacy reason we used image id such as `xxxxxx?ts=123456`
Using Thumbor 1.5.2 it works well storing s3 object just like `s3://.../xxxxxx?ts=123456`

since Thumbor 6 and tc-aws corresponding version, those image are not available any more, tc-aws is looking for `xxxxxx` (removing paramater from id)

I tried using encoded URL with "xxxxxx%3Fts=123456" id in URL but now of course tc-aws looks for `s3://.../xxxxxx%3Fts%3D123456` (that does not exists either)

Any clue to handle this ?
Add some retry with a special toggle in config maybe ?

**Comment by Bladrak** [comment]
The path where the image is stored and retrieved is computed through the ``_normalize_path`` function (https://github.com/thumbor-community/aws/blob/master/tc_aws/aws/storage.py#L250). The code doesn't seem to indicate any filtering of parameters though... 
Did you try the same operation with a file storage for instance? Did you encounter the same issue?

**Comment by dhardy92** [comment]
my guess is maybe this https://github.com/thumbor/thumbor/commit/db2ba7e8ecc881624f19b4c3480adb48e3d9f15f#diff-d6e26a4d657e793a39b503dfd6728738R35 was the change that cause me problems.

@guilhermef any reason why using only path and not full uri anymore ?

**Comment by dhardy92** [comment]
sadly, revert to `url = self.request.uri` does not fix the problem

**Comment by dhardy92** [comment]
I think this is my guilty commit at https://github.com/thumbor/thumbor/commit/a1db568b6ffdf5547700c6ad8036842fd42c4d36#diff-f0814d1615dc4fba57d2fce889be3402L182

Apparently I am not the only one using query string in image id. /o\
