### ISSUE TITLE
Using sha1 hashes as filenames

### ISSUE THREAD

**Issue by juris** [thumbor-community/aws#60]
Would be great to have an option to use digest hash as filenames, as it was with willtrking's version.

As per [aws best practices](http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html) it is not performance efficient with the current schema, when object is stored with its original filename.

**Comment by Bladrak** [comment]
To comply with the best practices, we should rather suggest that the user uses CloudFront as in http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html#get-workload-considerations, given the workload should rather be GET-request intensive (as the cache is only written once).

The suggestion of adding an hash as a key prefix (not the full key) is rather for a mix of request types (GET but also PUT/POST/DELETE), which may be the case in some implementations of thumbor, but is rather limited IMO. The option could be added though, for those implementations, to add a hash prefix to the file key.

**Comment by dhardy92** [comment]
I suppose UUID key usage on POST requests is enough chaotic.
Problem exists on loader + storage when very heavily used as @Bladrak suggests.

**Comment by Bladrak** [comment]
Closing this issue as there hasn't been much activity on it. Feel free to re-open if it happens again.
