### ISSUE TITLE
Retry on HTTP 5xx errors.

### ISSUE THREAD

**Issue by mguillet** [thumbor-community/aws#63]
Sometimes S3 calls fail with a 5xx error code. According to the S3 documentation these errors can happen and we can retry the request: it should work eventually!

I'm thinking specifically about fetching images from S3.

Would it be possible for the s3_loader to retry on 5xx error?

**Comment by Bladrak** [comment]
Should be pretty easy to do yes, but harder to test though... Would you like to contribute by submitting a PR? I'd say the error handling on s3 loading would be performed here: https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/s3_loader.py#L35 so we can retry in here (but we'd need to avoid an infinite retry loop)

**Comment by aoqfonseca** [comment]
How much retries? Did this should be in config?

**Comment by aoqfonseca** [comment]
I can do this issue.

**Comment by Bladrak** [comment]
Thanks for offering :) Indeed, I think the number of retries should be in configuration, with a default to 0 (so it's backwards compatible). Would that seem ok to you?

**Comment by aoqfonseca** [comment]
This is ok.

**Comment by aoqfonseca** [comment]
I finished and I opened a pull request  (#71). Tks !

**Comment by aoqfonseca** [comment]
News about my pull request?

**Comment by Bladrak** [comment]
@aoqfonseca I've reviewed it, waiting on your feedback on the PR :)

**Comment by Bladrak** [comment]
Has been released under version 6.0.3 :)

**Comment by aoqfonseca** [comment]
Tks for this opportunity and all review made.

I'll try to help more.
