### ISSUE TITLE
versionId

### ISSUE THREAD

**Issue by kshipp** [thumbor-community/aws#66]
Any planned support for AWS S3 object versionId?  I didn't see anything regarding this in the doc or code.

**Comment by Bladrak** [comment]
Hi @kshipp :)

Can you be more explicit? What would be the use case for this?

Thanks!

**Comment by kshipp** [comment]
In case you're not aware, S3 offers versioning of objects.  Thumbor doesn't allow for the passing of the version of the object (versionid), so it's defaulting to the original version of the object to create the thumb. If the object has, for example, 5 versions, there's currently no way to get a thumb created from the latest version because there's no way to pass the versionid.... unless there's something I'm missing.  :)

**Comment by Bladrak** [comment]
Ok I see, however as you mentioned, I don't see versioning supported in thumbor. So I don't see how we could handle it on the AWS connector for now (unless there's something I'm missing?).
