### ISSUE TITLE
use thumbor_aws with s3 compatible server

### ISSUE THREAD

**Issue by vmalaga** [thumbor-community/aws#67]
Hi.

we are begining with thumbor and would like use this plugin to save result images on a bucket on our s3 compatible cluster. 
Is possible to modify the url of the server hosting the bucket ?

using s3cmd the param is host_base

regards

**Comment by Bladrak** [comment]
Hello,

Could you be more specific about what you want to achieve?

On the current version, you're able to specify:
* the bucket name for the result storage
* the bucket path for the result storage

What would you like to specify?

**Comment by vmalaga** [comment]
Hi @Bladrak 

we have a s3 compatible cluster of riak-cs http://docs.basho.com/riak/cs/2.1.1/ we can use any s3 compatible tool or api with it ( s3cmd, boto )

So what i need is specify the host or endpoint the plugin have to connect.

I have seen a fork of this repo implementing it, but i prefer to use the oficial aws plugin if is possible.

https://github.com/kevinmusker/aws/tree/custom_endpoint

**Comment by Bladrak** [comment]
Oh ok, didn't know about this solution :) 

Seems like a good addition indeed, maybe you could ask @kevinmusker for a PR? Otherwise we'll implement it on our side.

**Comment by vmalaga** [comment]
ok thanks

**Comment by danielmotaleite** [comment]
Just one update to help search engines :)
Merged done, you can change the endpoint by using this parameter:

```TC_AWS_ENDPOINT=http://your.endpoint.url/```
