### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by leonardyhuang** [thumbor-community/aws#69]
Hi,

I could not get the metadata (always times out), example : **server.url/unsafe/meta/images/filename.jpg** or **server.url/unsafe/meta/fit-in/0x0/images/filename.jpg**.

Is this an issue, or I have to change my configuration?

Thanks.

**Comment by Bladrak** [comment]
Hello.

Might be an issue, but without the error log I can't tell you for sure... Could you provide it? 

Thanks :)

**Comment by aoqfonseca** [comment]
@130nrd 

Any new about this issue? Can you send to us a log with the error you got?
