### ISSUE TITLE
RESULT_STORAGE_EXPIRATION_SECONDS

### ISSUE THREAD

**Issue by christophlingg** [thumbor-community/aws#72]
First of all, thank you guys for your great work!

The [documentation of thumbor](https://github.com/thumbor/thumbor/wiki/Configuration#result_storage_expiration_seconds) distinguish between expiration of storage and result storage:

 - `RESULT_STORAGE_EXPIRATION_SECONDS`
 - `STORAGE_EXPIRATION_SECONDS`

In comparison tc_aws does not distinguish between and considers `STORAGE_EXPIRATION_SECONDS` for the result storage too.

**Comment by aoqfonseca** [comment]
@christophlingg 

We'll fix this. Thanks!
