### ISSUE TITLE
Can't load images using s3_loader

### ISSUE THREAD

**Issue by arthens** [thumbor-community/aws#78]
I'm using https://github.com/APSL/docker-thumbor with `tc_aws.loaders.s3_loader`, but I can't seem to get it to work. The error I'm getting is:

```
2016-11-22 09:26:57 thumbor:ERROR [BaseHandler] get_image failed for url `bucket-name/design-example-1.jpg`. error: `Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"`
2016-11-22 09:26:57 tornado.access:ERROR 500 GET /PbhAZkbZdM0Q5AWPztSfaFdalNY=/fit-in/500x500/bucket-name/design-example-1.jpg (172.31.1.220) 39.45ms
```

which seems to imply that it's failing to extract the bucket name from my url... is the url I'm generating wrong or is this a bug/configuration problem?

Thanks

**Comment by Bladrak** [comment]
Seems you're missing some configuration, but I guess you should open an issue on APSL/docker-thumbor for that :)

**Comment by arthens** [comment]
Will do, thank you!

**Comment by arthens** [comment]
Turns out that `apsl/docker` defaults `TC_AWS_LOADER_BUCKET` to an empty string instead of `None`, which was causing `s3_loader` to ignore the bucket in the url
