### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by benzon** [thumbor-community/aws#81]
Im looking in to thumbor combined with AWS.

What is unclear to me, or i may not understand, is would i be able to load the image in direct from the S3 storage with out enabling http access to the S3 Bucket?

I got 7500 images right now on S3, and i would love to be able to just more or less load the images directly from there would that be possible?

**Comment by Bladrak** [comment]
You can indeed, by using the loader :) This one https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/s3_loader.py loads directly from s3 whereas this one https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/presigning_loader.py uses pre-signed URLs.

**Comment by benzon** [comment]
Perfect! Trying to set it all up now :D

**Comment by benzon** [comment]
Bladrak do you know if i run in to problems if there is some where you can pay for help setting it all up ?

**Comment by benzon** [comment]
Bladrak think i got it up and running, just need a bit of help here, i wanna use the php lib https://github.com/99designs/phumbor

How would i call the image just put in the image name or how ?

**Comment by Bladrak** [comment]
Good luck for the setup! Regarding the support, I'm not aware of a company doing that, but maybe you can find some freelancers?

For the image, the reference depends on the loader you're using. If it's S3, you should put the S3 key name for the image reference (relative to the loader path you've configured in thumbor).

**Comment by benzon** [comment]
It's the S3 loader :)

Oh had one more question, if i want to use the upload part in Thumbor would i be able to set that up with AWS to ?

**Comment by Bladrak** [comment]
Never tried it myself but you should be, yes.

**Comment by dhardy92** [comment]
Yes it does
