### ISSUE TITLE
Image Urls without filename do not store in S3

### ISSUE THREAD

**Issue by philipbjorge** [thumbor-community/aws#85]
`thumbor/unsafe/400x0/filters:format(png)/https://d3ix816x6wuc0d.cloudfront.net/i/372852/`

That URL creates an empty directory in S3 rather than storing the image when using `storages.s3_storage`

Removing the slash, does work -- `thumbor/unsafe/400x0/filters:format(png)/https://d3ix816x6wuc0d.cloudfront.net/i/372852`

**Comment by aoqfonseca** [comment]
This happens because we use image path to construct S3 path. When you put the last slash, S3 consider this a folder then create an empty folder (w/o name). We'll check a way to manage this kind of issue.

Thanks.

**Comment by philipbjorge** [comment]
@aoqfonseca -- So we have extensionless image urls and need a fix for this.
Off the top of my head, it seems like doing a transformation like the following...

`https://xyz.cloudfront.net/i/372852/` to `https://xyz.cloudfront.net/i/372852SLASH` would work (or any sort of ending that we are relatively certain won't have collisions)

Can you think of any problem with that approach on our side?

**Comment by aoqfonseca** [comment]
No problem with this approach. I would rather to use something more meaningful, like: https://xyz.cloudfront.net/i/372852/image.png or https://xyz.cloudfront.net/i/372852.png  .

**Comment by philipbjorge** [comment]
@aoqfonseca -- The problem with appending the extension is that I don't think we know what file type an image is at `_normalize_path` -- I went with the following approach...

https://github.com/Leafly-com/aws/pull/1/files

@Bladrak -- If this seems solid, I'll write tests and send out a PR.

**Comment by Bladrak** [comment]
Seems fine @philipbjorge, however I would rename ``no_extension`` to ``root_image`` (without the type as the extension). Also, this name may rather be in the config, so it can be changed by the use if need be.

**Comment by Bladrak** [comment]
@philipbjorge What's the status on this? Do you feel ready to submit a PR to this repo?

**Comment by philipbjorge** [comment]
@Bladrak -- Heh, I'd forgotten about this.
I will try to get to this within 7 days, but if I haven't submitted a PR for this by then anyone should feel free to pick this up :).

It's a straight forward feature to add and would be great for new contributors to open source.

**Comment by Bladrak** [comment]
Great, thanks for your feedback :)

**Comment by Bladrak** [comment]
Should be resolved with 6.2.3 version.
