### ISSUE TITLE
PUT timeout behind proxy

### ISSUE THREAD

**Issue by Xrampino** [thumbor-community/aws#89]
EDIT : I found that the problem is related to tornado-botocore which

- Doesn't use `CurlAsyncHTTPClient` by default (tornado states that `Proxies are currently only supported with curl_httpclient`)
- Doesn't pass proxy env var in `HTTPRequest`

I created a pull request https://github.com/nanvel/tornado-botocore/pull/9
Feel free to close this issue.

---------------------------

While the loader works properly while setting `$https_proxy` env var, I can't seem to have the upload working when using the `/image` endpoint.

It works fine when using aws-cli and `aws s3 sync` (newer version of botocore though).
It also works using botocore API directly (still 1.2.0 as indicated by tornado-botocore) : 

````
s3 = session.create_client('s3', region_name=region)
fp = open('./' + filename, 'rb')
s3.put_object(Body=fp,Key='testkey',Bucket=bucket)
````

Using tc_aws, the image itself is properly uploaded to the local server, and the PUT call is made, but I have no response from AWS.

**Comment by Bladrak** [comment]
Thanks for adding the details :) Closing.
