### ISSUE TITLE
Instance loader or storage cache

### ISSUE THREAD

**Issue by estahn** [thumbor-community/aws#9]
All images are currently loaded from S3, which is basically the source. It would be useful to be able to specify some kind of local storage (e.g. local cache) in order to reduce the amount of requests to AWS S3. We're currently mitigating this issue with a local nginx proxy with a defined cache size.

Variables | Default | Description
------ | --------- | ------
AWS_LOCALCACHE_STORAGE | thumbor.storages.file_storage | |
AWS_LOCALCACHE_STORAGE_EXPIRATION_SECONDS | 0 | Determine the time in seconds that a file is considered to be expired. 0 disables expiration. |
AWS_LOCALCACHE_STORAGE_SIZE | 1024 | Size of the local cache. Oldest files will be deleted first. |

**Comment by masom** [comment]
Thumbor already supports doing this with Storages. You could use the AWS loader and the file_storage/file_result_storage to accomplish this.

**Comment by Bladrak** [comment]
@estahn is @masom answer satisfying? Or do you need more information/have a feedback you wish to share?

**Comment by estahn** [comment]
@masom @Bladrak I guess the answer is valid, not satisfying in a sense that it provides a replacement for nginx cache though ;)

See http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path

I assume it makes more sense to use nginx then to reinvent the wheel.

**Comment by Bladrak** [comment]
Yes indeed, coupling that with the file storage for result storage may be a good option :)
