### ISSUE TITLE
TC_AWS_LOADER_BUCKET = "None"

### ISSUE THREAD

**Issue by danielmotaleite** [thumbor-community/aws#90]
As in issue #78 , this thumbor-aws also have the same "problem", so i suggest that the text be changed:

```

# S3 bucket for Loader. If given, source urls are interpreted as keys
# within this bucket. If set to "None", source urls are expected to contain
# the bucket name, such as 's3-bucket/keypath'.
```

That is, remove the `not given` and put `set to "None"` , this way users will be able to set the correct option and not a Null

**Comment by Bladrak** [comment]
Actually, the value must not be set in order to have the value ``None``. If you set it to ``"None"``, it's value will be the string ``"None"`` which won't work. So we need it to be not set, which is different than being set to ``""`` or ``"None"``.

**Comment by danielmotaleite** [comment]
Ok, probably, as i'm hitting the signature problem in riak, i still didn't manage to really fetch the image.

So probably change the text to `If not given (ie: commented out)`` so it is easier to understand what state the option accepts

**Comment by Bladrak** [comment]
Sure :) Will try to do that when I find the time, unless you want to submit a PR?
