### ISSUE TITLE
Using thumbor-aws with riak

### ISSUE THREAD

**Issue by danielmotaleite** [thumbor-community/aws#91]
I'm trying to use thumbor-aws with riak that is mostly s3 compatible.

Sadly it still do not support aws signatures v4, only v2, so i get this:

```
{'ResponseMetadata': {'HTTPStatusCode': 400}, 'Error': {'Message': 'The authorization mechanism you have provided (AWS4-HMAC-SHA256) is not supported.', 'Code': 'InvalidRequest', 'Resource': '/None/static-bd/BB.png'}}
```

So how can i force thumbor to use V2 instead? i tried to add to the `$AWS_CONFIG_FILE` the option `signature_version = 'v2'`, but it does not seem to work. Do i need to some some parameter also in thumbor-aws?

thanks

**Comment by Bladrak** [comment]
Hello,

Most of the configuration is done through boto3, so I guess you should look there for integrating it with riak. I never tried it on my side, so I won't be of much help to you, sorry.

**Comment by danielmotaleite** [comment]
Found a way, on my docker imagens i have this file:

```
# cat  /root/aws.credentials 
[default]
aws_access_key_id = (KEY)
aws_secret_access_key =(SECRET)
s3 =
    signature_version = s3
```
Then i do 
```
AWS_CONFIG_FILE=/root/aws.credentials
export AWS_CONFIG_FILE
```

And start thumbor... this fixed the auth error above
With the comment out of TC_AWS_LOADER_BUCKET, so i can use the bucket name from the url, i can finally use thumbor-aws with riak

Can you add some of this info to your documentation, so others will not hit this problem too :)

**Comment by Bladrak** [comment]
Sure, I'll try to do that when I've got the time, unless you're willing to submit a PR?
