### ISSUE TITLE
Change S3 url through environment variable

### ISSUE THREAD

**Issue by volyx** [thumbor-community/aws#93]
I want to use minio as S3 storage. https://minio.io/

Minio implements Amazon S3 v4 APIs. I think, that I just can change url from %amazon_s3_url% to %minio_url% and everything will work.

What do you think about it?

**Comment by Bladrak** [comment]
There is already a ``TC_AWS_ENDPOINT`` config option that should allow you to switch to minio, given their API is compatible. However, this is not editable through env var, but through your Thumbor configuration.

**Comment by volyx** [comment]
Thank you!

**Comment by pscheit** [comment]
So @volyx did it work?
Thinking about minio as well. Any learnings?

**Comment by volyx** [comment]
Yes, It did as I remembered. I moved to imgproxy quickly

вс, 22 мар. 2020 г., 20:31 Philipp Scheit <notifications@github.com>:
