### ISSUE TITLE
ALLOWED_SOURCES option ignored with TC_AWS_ENABLE_HTTP_LOADER enabled?

### ISSUE THREAD

**Issue by smagnaschi** [thumbor-community/aws#94]
It seems to me that ALLOWED_SOURCES is ignored with the TC_AWS_ENABLE_HTTP_LOADER option enabled.
If I load thumbor with the http_loader it correctly whitelist the hosts specified in ALLOWED_SOURCES, while with the S3 loade with http support this isn't the case.
Is there a specific parameter to allow the http sources, or am I missing something?
Thanks!

**Comment by Bladrak** [comment]
Hello,
Sorry for the delay. You're right, it seems we don't check whether the URL is valid or not using the HTTP loader. We'll try to fix this.
