### ISSUE TITLE
ImportError: cannot import name Botocore

### ISSUE THREAD

**Issue by thenrikie** [thumbor-community/aws#99]
I got an error when starting thumbor after install tc_aws
```
    from tornado_botocore import Botocore
ImportError: cannot import name Botocore
```
now `pip install tc_aws` will always install the lastest version of tornado_botocore.
When I try to reinstall tornado_botocore with version 1.0.0, the problem goes away.

setup.py should lock tornado_botocore to version 1.0.0

**Comment by Bladrak** [comment]
Thanks for reporting the issue. Would you mind submitting a PR with the fix? Otherwise I'll try to do this when I've got some time.

**Comment by sami9gag** [comment]
Sure thing.. PR created.

**Comment by Bladrak** [comment]
Thanks!
